#!/usr/bin/env python3
import argparse
import binascii
import sys

from pybitcoin import key_utils

def main(args):
  parser = argparse.ArgumentParser(description='Generate a bitcoin wallet.')
  parser.add_argument('--random', action='store_true', default=False)
  options = parser.parse_args(args)

  if options.random:
    private_key = key_utils.get_random_private_key()
    print('Random private key: %s' % binascii.hexlify(private_key))
  else:
    private_key_str = input('Enter your private key (32 hex digits): ')
    private_key = key_utils.get_private_key(private_key_str)
  print('Wallet import format of private key: %s' %
        key_utils.get_wallet_import_format(private_key))
  print('Your public address: %s' % key_utils.get_btc_address(private_key))


if __name__ == '__main__':
  sys.exit(main(sys.argv[1:]))

