#!/usr/bin/env python3

from pybitcoin import key_utils

if __name__ == '__main__':
  private_key_str = input('Enter your private key (32 hex digits): ')
  private_key = key_utils.get_private_key(private_key_str)
  print('Wallet import format of private key: %s' %
        key_utils.get_wallet_import_format(private_key))
  print('Your public address: %s' % key_utils.get_btc_address(private_key))

